services:
  - type: web
    name: tecnovend-api
    env: node
    region: ohio
    plan: starter
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.18.0
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
